### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by ReiVanBjair** [titu1994/Inception-v4#7]
Whenever I try to run this:

> from inception_v4 import create_inception_v4
> model = create_inception_v4()

I get the error:
Traceback (most recent call last):

  File "<ipython-input-10-f440fc3fa132>", line 1, in <module>
    runfile('C:/Users/ReiVanBjair/.spyder-py3/temp.py', wdir='C:/Users/ReiVanBjair/.spyder-py3')

  File "C:\Users\ReiVanBjair\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\ReiVanBjair\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ReiVanBjair/.spyder-py3/temp.py", line 11, in <module>
    model = create_inception_v4()

  File "C:\Users\ReiVanBjair\Documents\FaceRecog\inception_v4.py", line 190, in create_inception_v4
    x = inception_stem(init)

  File "C:\Users\ReiVanBjair\Documents\FaceRecog\inception_v4.py", line 45, in inception_stem
    x = merge([x1, x2], mode='concat', concat_axis=channel_axis)

TypeError: 'module' object is not callable

**Comment by ReiVanBjair** [comment]
Update: I tried removing the parenthesis at create_inception_v4() and it worked.

**Comment by holianh** [comment]
still not working, 
but when I define a function like this:

```python
from keras.layers.merge import concatenate

def merge(inputs, mode, concat_axis=-1):
    return concatenate(inputs)
```
everything running fine. 
P/S: I used Channel last, if you want to use channel first, just add axis to concatenate fn
