### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by dmjeong1995** [titu1994/Inception-v4#9]
Hi
whenever I try to run your code Inception_resnet_v2.py
this error is occured

Using TensorFlow backend.
Traceback (most recent call last):
  File "inception_resnet_v2.py", line 251, in <module>
    inception_resnet_v2 = create_inception_resnet_v2()
  File "inception_resnet_v2.py", line 208, in create_inception_resnet_v2
    x = inception_resnet_stem(init)
  File "inception_resnet_v2.py", line 50, in inception_resnet_stem
    m = merge([c1, c2], mode='concat', concat_axis=channel_axis)
TypeError: 'module' object is not callable

The only one change in my code is python version(I'm 3.x)

**Comment by TaeheeJeong** [comment]
I have same issue for inception_v4.py
